"""마크다운 → HTML → Playwright Chromium PDF.

이 시스템엔 이미 Playwright Chromium이 wisereport 자동화용으로 메모리에 있어
별도 PDF 라이브러리(weasyprint 등) 추가 불필요. HTML→PDF는 browser.pdf()로
한국어 폰트 (fonts-noto-cjk 시스템 설치됨) 자연스럽게 처리.

사용:
    from src.pdf_export import markdown_to_pdf
    pdf_path = await markdown_to_pdf(md_text, title="비교 분석", output_path=...)
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

log = logging.getLogger(__name__)

# 한국어 + 마크다운 표·코드블록 보기 좋게.
CSS = """
@page { size: A4; margin: 18mm 15mm; }
body { font-family: "Noto Sans CJK KR", "Noto Sans KR", sans-serif;
       font-size: 11pt; line-height: 1.55; color: #222; }
h1 { font-size: 20pt; color: #111; border-bottom: 2px solid #333;
     padding-bottom: 6pt; margin-top: 0; }
h2 { font-size: 15pt; color: #1a4480; margin-top: 18pt;
     border-left: 4px solid #1a4480; padding-left: 8pt; }
h3 { font-size: 12pt; color: #333; margin-top: 12pt; }
p { margin: 6pt 0; }
ul, ol { margin: 6pt 0; padding-left: 20pt; }
li { margin: 3pt 0; }
table { border-collapse: collapse; width: 100%; margin: 10pt 0; font-size: 10pt; }
th, td { border: 1px solid #aaa; padding: 5pt 8pt; text-align: left; }
th { background: #f0f4fa; font-weight: 600; }
code { font-family: "Noto Sans Mono CJK KR", "Courier New", monospace;
       background: #f5f5f5; padding: 1pt 4pt; border-radius: 3pt;
       font-size: 9.5pt; }
pre { background: #f8f8f8; border: 1px solid #ddd; padding: 8pt;
      border-radius: 4pt; font-size: 9pt; overflow-x: auto; }
pre code { background: transparent; padding: 0; }
blockquote { border-left: 3px solid #ccc; padding-left: 10pt;
             color: #555; margin: 8pt 0; }
hr { border: none; border-top: 1px solid #ddd; margin: 14pt 0; }
strong { color: #111; }
.footer { font-size: 8pt; color: #888; text-align: right;
          margin-top: 20pt; border-top: 1px solid #eee; padding-top: 4pt; }
"""


def _wrap_html(md_text: str, title: str) -> str:
    """마크다운 → HTML wrap (CSS inline)."""
    import markdown as md
    body = md.markdown(
        md_text,
        extensions=["tables", "fenced_code", "nl2br", "sane_lists"],
    )
    return f"""<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="utf-8">
  <title>{title}</title>
  <style>{CSS}</style>
</head>
<body>
{body}
<div class="footer">Generated by basketball-rag-agent · {title}</div>
</body>
</html>
"""


async def markdown_to_pdf(
    md_text: str,
    output_path: Path,
    title: str = "분석 리포트",
) -> Optional[Path]:
    """마크다운 → PDF. 성공 시 path, 실패 시 None.

    Playwright async API 사용. 이미 다른 곳에서 PIPELINE_LOCK 안의 wisereport
    세션과 충돌하지 않게, 본 함수는 별도 Chromium instance를 새로 띄움 (가벼움).
    """
    try:
        from playwright.async_api import async_playwright
    except Exception:
        log.exception("playwright import 실패 — PDF 생성 불가")
        return None

    html = _wrap_html(md_text, title)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        async with async_playwright() as p:
            browser = await p.chromium.launch(headless=True)
            try:
                page = await browser.new_page()
                await page.set_content(html, wait_until="networkidle")
                await page.pdf(
                    path=str(output_path),
                    format="A4",
                    print_background=True,
                    margin={"top": "18mm", "bottom": "18mm", "left": "15mm", "right": "15mm"},
                )
            finally:
                await browser.close()
    except Exception:
        log.exception("Playwright PDF 생성 실패")
        return None

    if not output_path.exists() or output_path.stat().st_size < 1000:
        log.warning("PDF 생성됐으나 비정상 (size=%d)", output_path.stat().st_size if output_path.exists() else 0)
        return None
    return output_path
